name: transit_cljd

description: >-
  This library provides support for marshalling Transit data to/from
  ClojureDart.

version: 0.8.6

repository: https://github.com/wevre/transit-cljd

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  transit_dart: ^0.8.81

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
